--DDL DATA DEFINITION LANGUAGE

CREATE DATABASE Exercicios;

USE Exercicios;

CREATE TABLE Genero
( IdGenero INT PRIMARY KEY IDENTITY,
  NomeGenero VARCHAR(100)
)

CREATE TABLE Filme
( IdFilme INT PRIMARY KEY IDENTITY,
  IdGenero INT FOREIGN KEY REFERENCES Genero (IdGenero),
  TituloFilme VARCHAR(100)
  )