--DDL - DATA DEFINITION LANGUAGE

--CRIA UM BANCO DE DADOS
CREATE DATABASE Teste;
--USA O BANCO DE DADOS
USE Teste;

--CRIA UMA TABELA
CREATE TABLE Funcionarios(

IdFuncionario INT PRIMARY KEY IDENTITY,
Nome VARCHAR(100)
)
CREATE TABLE Empresas
(  IdEmpresa INT PRIMARY KEY IDENTITY,
   IdFuncionario INT FOREIGN KEY REFERENCES Funcionarios(IdFuncionario),
   NomeEmpresa VARCHAR(100)
   )


--ALTERA A TABELA
ALTER TABLE Funcionarios
--EXCLUI A COLUNA
DROP COLUMN Nome;

DROP TABLE Funcionarios;

DROP DATABASE Teste;